load ../tool2 .
load bakery .

mod MODEL is
  pr BAKERY .
  inc SATISFACTION .
  inc OBSERVATION .

  subsort Conf < State .

  var S : State .
  var PS : ProcSet .  vars N N' M M' : Nat . 

  --- Defining State Propositions ---
  op twoCrits : -> Prop [ctor] . --- goal
  eq N ; M ; [crit(N')] [crit(M')] PS |= twoCrits = true .
  eq S |= twoCrits = false [owise] .

  op wakeLHS : -> Prop [ctor] .
  eq N ; M ; [idle] PS |= wakeLHS = true .
endm