--- Lamport's Bakery protocol in Maude.
--- From: All About Maude - A High-Performance Logical Framework. 
fmod BAKERY-SYNTAX is 
  pr NAT .
  sorts ModeIdle ModeWait ModeCrit Mode . 
  subsorts ModeIdle ModeWait ModeCrit < Mode . 
  sorts ProcIdle ProcWait Proc ProcIdleSet ProcWaitSet ProcSet . 
  subsorts ProcIdle < ProcIdleSet . 
  subsorts ProcWait < ProcWaitSet . 
  subsorts ProcIdle ProcWait < Proc < ProcSet . 
  subsorts ProcIdleSet < ProcWaitSet < ProcSet . 

  op idle : -> ModeIdle . 
  op wait : Nat -> ModeWait . 
  op crit : Nat -> ModeCrit . 
  op `[_`] : ModeIdle -> ProcIdle . 
  op `[_`] : ModeWait -> ProcWait . 
  op `[_`] : Mode -> Proc . 

endfm