***(
    pta-base.maude
    --------------

    The module MODEL-BASE must be imported by the module defining the rules
    of the PTA at hand. 

    The following sorts are defined:

    - NState   : a state where it is possible to perform a delay transition
    - DState   : the resulting state after a delay transition
    - State    : for delayed and non-delayed states
    - Location : locations of the PTA
    - DCTerm   : constrained terms of the form t | C where C is a Boolean
                 expression and t a term of sort DState
    - NCTerm   : constrained terms of the form t | C where C is a Boolean
                 expression and t a term of sort NState
    - CTerm    : for constrained terms of the form t | C
    - SCTerm   : for sets of CTerm (used in the outputs of the analyses)

    States of the system are user defined constructors of sort State
    In order to use the new implemented command reachability (see meta-pta), 
    the definition of the PTA must implement equations (not used for
    smt-search) to define the operator get-location. 

*)

load smt .
--- load smt-check . --- MaudeSE

mod MODEL-BASE is

    --- States 
    sorts State DState NState  .
    subsort DState NState < State .
    
    --- Locations
    sort Location .

    --- Constrained terms 
    sort CTerm DCTerm NCTerm .
    subsort DCTerm NCTerm < CTerm .

    --- Lists of constrained terms 
    sort SCTerm .
    subsort CTerm < SCTerm .

    op error : -> SCTerm .  --- For meta-level operations

    --- Constrained terms 
    op _|_ : DState  Boolean -> DCTerm [prec 99 format(n d d d )].
    op _|_ : NState  Boolean -> NCTerm [prec 99 format(n d d d )].

    --- This symbol is only used to build the final solution (from meta-term
    --- to terms in the sort CTerm (see ./meta-pta.maude)
    op _;;_ : SCTerm SCTerm -> SCTerm [ctor assoc ] .

    --- This operation must be implemented by the PTA at hand
    --- it is only needed for the new command reachability 
    op get-location : State -> Location .
endm

