***
***	Maude term abstraction module.
***
*** Abstracting Boolean, Integer, Real term.
*** abstracting constants to new variables.
***
fmod TERM-ABST is
  protecting META-LEVEL .
  protecting CONVERSION .
 
  sort TermAbstraction .
  op {_,_,_} : TermList Condition Nat -> TermAbstraction [ctor format (b! o d d d d b! o)] .

  var M : Module .
  var N N' N'' : Nat .
  var F : Qid .
  var TY : Type .
  var TYS : TypeSet .
  var C : Constant .
  vars Cd Cd' : Condition .
  vars V NV : Variable .
  var T : Term .
  vars TL TL' : TermList .
  vars NTL : NeTermList .
  
endfm