***(
    Coffee Machine
    --------------

    Using strategies to control that at least a dose of sugar is needed
    It must be run with Maude SE https://maude-se.github.io/

*)

load smt
load smt-check

mod PTA-COFFEE is
    pr SMT-CHECK .
    inc NAT .
    pr QID .

    --- Fresh variables
    subsort Nat < SMTVarId .
    subsort Qid < SMTVarId .

    --- ---------------------------
    vars x y z     : RealExpr .
    vars x' y' z'  : RealExpr .
    vars p1 p2 p3  : RealExpr . 
    var t          : RealExpr .
    var N          : Nat .
    vars C C'      : BooleanExpr .
    --- ---------------------------

    sorts State State' Location .

    --- Global configuration
    op <_|_|_> : Nat BooleanExpr State'  -> State .

    --- Configurations
    ops idle sugar coffee done : -> Location .
    op <_;_;_> <_;_;_> : Location RealExpr RealExpr RealExpr RealExpr RealExpr  -> State' .
    op [_;_;_] <_;_;_> : Location RealExpr RealExpr RealExpr RealExpr RealExpr  -> State' .

endm