load pta-base .

mod MODEL is
    inc MODEL-BASE .
    pr REAL .

    --- --------------------------
    vars X1 X2        : Real .
    vars X1' X2'      : Real .
    vars P1 P2 P3     : Real .
    var  T            : Real . 
    var  L            : Location .
    --- --------------------------

    ops idle sugar coffee done : -> Location .

    op <_:_;_> <_;_;_> : Location Real Real Real Real Real -> NState .
    op [_:_;_] <_;_;_> : Location Real Real Real Real Real -> DState .

endm

--- load meta-pta .

--- red reachability( (< idle : T:Real ; T:Real >   < P1:Real ; P2:Real ; P3:Real > 
---                     | T:Real >= 0/1 and P1:Real >= 0/1 and P2:Real >= 0/1 and P3:Real >= 0/1 and 
---                       2/1 * P1:Real > P2:Real)) .
