***(
    Infinite states
    --------------

    EXample in Figure 3b (infinite number of states)
    The location BAD is not reachable and the search command loops (see 
    the bounded limit in the smt-search command below)

*)
load pta-base .

mod MODEL is
    inc MODEL-BASE .
    pr REAL .

    --- ---------------------------
    vars X Y      : Real .
    vars X' Y'    : Real .
    vars T      : Real .
    --- ---------------------------

    --- Configurations
    ops l0 l1 bad : -> Location .
    op <_:_>  : Location Real   -> NState .
    op [_:_]  : Location Real   -> DState .

    crl [l0-l1] : 
        < l0 : X > =>
        [ l1 : X  ] 
        if ( 5/1 <= X and 10/1 >= X ) = true .

endm