***(
    Infinite states
    --------------

    EXample in Figure 3b (infinite number of states)
    The location BAD is not reachable 
    The command reachability finds the only 2 symbolic states in this PTA

*)
load pta-base .

mod MODEL is
    inc MODEL-BASE .
    pr REAL .

    --- ---------------------------
    vars X Y      : Real .
    vars X' Y'    : Real .
    vars T      : Real .
    --- ---------------------------
    
    --- Configurations
    ops l0 l1 bad : -> Location .
    op <_:_>  : Location Real   -> NState .
    op [_:_]  : Location Real   -> DState .

endm

