
***(
    Infinite states
    --------------

    Example in Figure 3a (infinite number of states)
    The location BAD is reachable in this case

*)

load smt .

mod EXAMPLE-INF is
    pr REAL .
    sorts State Location .

    --- ---------------------------
    vars X Y      : Real .
    vars X' Y'    : Real .
    vars T        : Real .
    --- ---------------------------

    --- Configurations
    ops l0 l1 bad : -> Location .
    op <_:_;_>  : Location Real Real   -> State .
    op [_:_;_]  : Location Real Real   -> State .
    
    crl [l0-l1] : 
        < l0 : X ; Y > =>
        [ l1 : X ; Y ] 
        if ( 1/1 <= X and 5/1 >= X ) = true .

endm