***(
    Infinite states
    --------------

    EXample in Figure 3b (infinite number of states)
    The location BAD is not reachable 
    The command reachability finds the only 2 symbolic states in this PTA

*)
load pta-base .

mod MODEL is
    inc MODEL-BASE .
    pr REAL .

    --- ---------------------------
    vars X Y      : Real .
    vars X' Y'    : Real .
    vars T      : Real .
    --- ---------------------------

    --- Configurations
    ops l0 l1 bad : -> Location .
    op <_:_>  : Location Real   -> NState .
    op [_:_]  : Location Real   -> DState .
    op {_:_}  : Location Real   -> TState .

    crl [l0-l1] : 
        < l0 : X > =>
        [ l1 : X  ] 
        if ( 5/1 <= X and 10/1 >= X ) = true .

    crl [l0-tick] : 
        [ l0 : X  ] =>
        < l0 : X + T  > 
        if (T >= 0/1) = true [nonexec] .

endm

