--- Peterson's Mutex algorithm for N process in Maude
--- from The Art of Multiprocessor Programming (Herlihy), p.28

fmod FILTER-SYNTAX is
  protecting NAT .

  sort Mode . --- idle wait(L) where L : current level
  ops on wait crit : -> Mode .

  sorts Proc ProcSet .
  subsort Proc < ProcSet .
  op proc : Nat Nat Mode -> Proc [ctor] . --- proc(PID, level, Mode)
  op __ : ProcSet ProcSet -> ProcSet [assoc comm] .

  sort Vict VictSet .
  subsort Vict < VictSet .
  op vict : Nat Nat -> Vict [ctor] . --- level, PID
endfm