load smt
load smt-check

mod ROBOT is
  pr REAL-EXPR .
  inc NAT .
  pr META-LEVEL .

  sort State .
  subsort Nat < SMTVarId .
  op {_,_,_} : BooleanExpr Nat Configuration -> State [ctor] .

  var N : Nat .
  vars O : Oid .
  vars CONST CONST' : BooleanExpr .
  vars PX VX AX PY VY AY PX' VX' AX' PY' VY' AY' T T' TAU : RealExpr .
  var ATTS : AttributeSet .

  --- move
  crl [move]:
      {CONST, N, 
       < O : C:Robot | pos  : [PX,  PY], 
                       vel  : [VX,  VY],
                       acc  : [AX,  AY],  
                       time : T, ATTS >}
   => {CONST', N + 5, 
       < O : C:Robot | pos  : [PX', PY'], 
                       vel  : [VX', VY'],
                       acc  : [AX,  AY], 
                       time : T + TAU, ATTS >}
    if TAU := r(N)
    /\ [PX', PY'] := [r(N + 1), r(N + 2)]
    /\ [VX', VY'] := [r(N + 3), r(N + 4)]
  --- accX

  --- accY
endm