fmod DINING-PHILOSOPHERS-BASE is
  protecting NAT .
  sorts Status .    
  ops think hungry single eat : -> Status [ctor] .

  op #N : ~> Nat .  --- total number of philosophers
  vars I J : Nat .  

  ops lc rc : Nat ~> Nat .    
  eq lc(I) = I .    
  ceq rc(I) = s(I) if (s(I) < #N) = true .
  ceq rc(I) = 0 if (s(I) == #N) = true .

  op adj : Nat Nat ~> Bool .
  eq adj(I,J) = (J == lc(I)) or (J == rc(I)) .
endfm