#!/usr/bin/env python3
import os
import argparse
import maudeSE.maude
from maudeSE.factory import Factory
# from maudeSE.hook.check import *
# from maudeSE.hook.search import *

if __name__ == '__main__':
    solvers = ["z3","yices","cvc5"]
    default_s = solvers[0]

    s_help = ["set an underlying SMT solver",
              "* Supported solvers: {{{}}}".format(",".join(solvers)),
              "* Usage: -s {}".format(solvers[-1]), "* Default: -s {}".format(default_s)]
    
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('file', nargs='?', type=str, help="input Maude file")
    parser.add_argument("-s", "-solver", metavar="SOLVER", nargs='?', type=str,
                        help="\n".join(s_help), default=default_s)
    parser.add_argument("-no-meta", help="no metaInterpreter", action="store_true")
    args = parser.parse_args()

    try:
        # instantiate our interface
        # factory = Factory()
        # factory.set_solver(args.s)
        # factorySetter = maudeSE.maude.SmtManagerFactorySetter()
        # factorySetter.setSmtManagerFactory(factory)
        maudeSE.maude.setSmtSolver(args.s)
        # maudeSE.maude.cvar.smtManagerFactory = Factory()
        maudeSE.maude.setSmtManagerFactory(Factory().__disown__())

        # initialize Maude interpreter
        maudeSE.maude.init(advise=False)

        # conv = factory.createConverter()
        # conn = factory.createConnector()
        # conv = conn.get_converter()

        # register special hooks
        # searchPathHook = SearchHook(conn, conv, path=True)
        # maudeSE.maude.connectEqHook('SmtSearchPathSymbol', searchPathHook)

        # load preludes

        # maudeSE.maude.load('smt.maude')
        # maudeSE.maude.load('smt-check.maude')

        # load an input file

        if args.file is None:
            raise ValueError("should provide an input Maude file")
        
        maudeSE.maude.load(args.file)

        if args.no_meta == False:
            maudeSE.maude.load('maude-se-meta.maude')

    except Exception as err:
        print("error: {}".format(err))