[project]
name            = 'maude-se'
version         = '0.0.4'
description     = 'Maude SMT Extension'
license.text    = 'GPLv3'
classifiers     = [
	'Intended Audience :: Science/Research',
	'Programming Language :: Python',
	'Programming Language :: Python :: 3',
	'Topic :: Scientific/Engineering',
	'Operating System :: MacOS',
	'Operating System :: POSIX :: Linux',
]
readme = 'README.md'
requires-python = '>=3.10,<3.15'
dependencies = [
	"pyyaml",
]

authors = [
	{name = "Geunyeol Yu", email = "maude-se@postech.ac.kr"},
]

[project.optional-dependencies]
z3 = ["z3-solver==4.13.0.0"]
cvc5 = ["cvc5==1.4.0"]
yices = ["yices==1.1.6", "yices-solver==2.6.5.post24"]
all-solvers = [
	"z3-solver==4.13.0.0",
	"cvc5==1.4.0",
	"yices==1.1.6",
	"yices-solver==2.6.5.post24",
]

[project.urls]
"Homepage"      = 'https://maude-se.github.io'
"Bug Tracker"   = 'https://github.com/postechsv/maude-se/issues'
"Documentation" = 'https://maude-se.github.io'
"Source Code"   = 'https://github.com/postechsv/maude-se'

[build-system]
requires = ['scikit-build-core', 'swig']
build-backend = 'scikit_build_core.build'

[project.scripts]
maude-se = "maudeSE:main"
maude-se-installer = "maudeSE.installer:main"
