[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "maude-se-native-z3"
version = "0.0.4"
description = "Native Z3 connector for Maude-SE"
requires-python = ">=3.10,<3.15"
dependencies = ["maude-se==0.0.4"]
license = {text = "GPL-3.0-only"}

[tool.setuptools]
packages = ["maude_se_native_z3"]

[tool.setuptools.package-data]
maude_se_native_z3 = ["*.dylib", "*.so", "licenses/*"]
